### ISSUE TITLE
Rain100 Datasets

### ISSUE THREAD

**Issue by Muccul** [jiupinjia/Deep-adversarial-decomposition#2]
How can I get the Rain Streak of  Rian100H datasets?
I used Rain Streak = Rain - Norain, but this Rain Streak doesn't equal what you give in demo

**Comment by jiupinjia** [comment]
Hi, 
The rain streaks of the Rain100H dataset I used are provided by their authors. You may download this dataset from https://github.com/ZhangXinNan/RainDetectionAndRemoval. If I am not wrong, the rain streaks are already there in this dataset.

**Comment by jiupinjia** [comment]
> How can I get the Rain Streak of Rian100H datasets?
> I used Rain Streak = Rain - Norain, but this Rain Streak doesn't equal what you give in demo

Hi,
The rain streaks of the Rain100H dataset I used are provided by their authors. You may download this dataset from https://github.com/ZhangXinNan/RainDetectionAndRemoval. If I am not wrong, the rain streaks are already there in this dataset.

**Comment by Muccul** [comment]
thanks
I have got Rain Streaks from https://github.com/ZhangXinNan/RainDetectionAndRemoval

**Comment by Getachew2023** [comment]
how can I get those datasets with out baidu cloud? Becase I can't sign up baidu. It says baidu can't support in Taiwan, Honkong and Macao.

**Comment by Algolzw** [comment]
Oh, the training images can be downloaded [here](http://www.icst.pku.edu.cn/struct/att/RainTrainH.zip).

**Comment by dlwns97** [comment]
> how can I get those datasets with out baidu cloud? Becase I can't sign up baidu. It says baidu can't support in Taiwan, Honkong and Macao.

Hi, did you receive datasets? I am also not in Taiwan, Honkong and Macao. So cannot use baidu cloud.
I am really looking forward to use these datasets.
Please anyone who can share the datasets?

Thanks.
