### ISSUE TITLE
which picture is the output of the DSC model?

### ISSUE THREAD

**Issue by nachifur** [jiupinjia/Deep-adversarial-decomposition#3]
This work is very meaningful. But I am confused about which picture is the output of the DSC model? The first line is input. The second line is your model output or DSC model output? The picture provided by https://openaccess.thecvf.com/content_CVPR_2020/supplemental/Zou_Deep_Adversarial_Decomposition_CVPR_2020_supplemental.pdf.
I will appreciate any reply from you. 
![image](https://user-images.githubusercontent.com/23144348/96676085-164ffa00-139f-11eb-90a3-518479b97cd2.png)

**Comment by jiupinjia** [comment]
> This work is very meaningful. But I am confused about which picture is the output of the DSC model? The first line is input. The second line is your model output or DSC model output? The picture provided by https://openaccess.thecvf.com/content_CVPR_2020/supplemental/Zou_Deep_Adversarial_Decomposition_CVPR_2020_supplemental.pdf.
> I will appreciate any reply from you.

Sorry, it was a mistake I made. The first row shows the input, the second row is our result. There should be a third row that shows the DSC's output but I accidentally missed it when saving the picture. Thanks for your careful read.

**Comment by nachifur** [comment]
Thank you for your reply.
