### ISSUE TITLE
DID-MDN test error

### ISSUE THREAD

**Issue by leno0903** [jiupinjia/Deep-adversarial-decomposition#5]
I have those dirs or files: './eval_output/.  /datasets/DID-MDN/val/1_input.jpg'
but display the error: [Errno 2] No such file or directory: './eval_output/./datasets/DID-MDN/val/1_input.jpg'

**Comment by jiupinjia** [comment]
> I have those dirs or files: './eval_output/. /datasets/DID-MDN/val/1_input.jpg'
> but display the error: [Errno 2] No such file or directory: './eval_output/./datasets/DID-MDN/val/1_input.jpg'

Hi, can you give a more detailed description of your problem? Are you trying to train or trying to test? and which command are you using? Thanks.

**Comment by leno0903** [comment]
(dad) amax@amax:~/a312/xcx/Deep-adversarial-decomposition$ python eval_derain.py --dataset did-mdn-test1 --ckptdir checkpoints --net_G unet_512 --save_output
initialize network with normal
loading the best checkpoint...
running evaluation...
/home/amax/a312/xcx/Deep-adversarial-decomposition/utils.py:1093: UserWarning: DEPRECATED: skimage.measure.compare_ssim has been moved to skimage.metrics.structural_similarity. It will be removed from skimage.measure in version 0.18.
  ssim = sk_cpt_ssim(tmp, tmp_gt)
Traceback (most recent call last):
  File "eval_derain.py", line 191, in <module>
    run_eval(args)
  File "eval_derain.py", line 164, in run_eval
    plt.imsave(os.path.join(args.output_dir, fname[:-4] + '_input.jpg'), img_mix)
  File "/home/amax/anaconda3/envs/dad/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2251, in imsave
    return matplotlib.image.imsave(fname, arr, **kwargs)
  File "/home/amax/anaconda3/envs/dad/lib/python3.6/site-packages/matplotlib/image.py", line 1605, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/amax/anaconda3/envs/dad/lib/python3.6/site-packages/PIL/Image.py", line 2148, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: './eval_output/./datasets/DID-MDN/val/1_input.jpg'

**Comment by jiupinjia** [comment]
You can replace the line 163 to
    fname = this_dir.split('/')[-1]
Tell me whether it works. Thansk.

**Comment by leno0903** [comment]
Thank you! It works.
