### ISSUE TITLE
Table 8 DSC [22] (TPAMI19) 7.100 in ISTD

### ISSUE THREAD

**Issue by nachifur** [jiupinjia/Deep-adversarial-decomposition#7]
![image](https://user-images.githubusercontent.com/23144348/97652961-9ca0c600-1a9a-11eb-8783-d6e2ee30a453.png)
7.1 is [8] Argan: Attentive recurrent generative adversarial network for shadow detection and removal.
[8] retrained DSC and got 7.1. 
But in DSC [22] (TPAMI19), is 6.67 in ISTD. 
![image](https://user-images.githubusercontent.com/23144348/97653229-3b2d2700-1a9b-11eb-86b3-206cf7c73929.png)
This should be a small citation error. If you plan to write this article into a journal, you can correct it. 
Your work is great and the code is complete!

**Comment by jiupinjia** [comment]
Thank you for your careful read! Yes, we will hopefully reorganize it and submit it to a journal. We will proof-read again and fix the citations correctly.
