### ISSUE TITLE
About the best_ckpt.pt

### ISSUE THREAD

**Issue by flyz1** [jiupinjia/Deep-adversarial-decomposition#8]
Sorry, my computer is too slow, and there is currently no fast enough training equipment. Can you share your trained models for deraining, reflection removal and shadow removal? Thanks a million!

**Comment by jiupinjia** [comment]
Hi @flyz1, thanks for your question. You can find the pre-trained models in the following link:
https://drive.google.com/drive/folders/1Tv4-woRBZOVUInFLs0-S_cV2u-OjbhQ-?usp=sharing
Please let me know if you have any questions. Thanks.

**Comment by flyz1** [comment]
I can't say How excited I am. Thank you very much for sharing your model with me. Wish you all the best in your academic research! Thanks again!

**Comment by jiupinjia** [comment]
It's my pleasure. I am closing this issue. Please feel free to reach out to me if you have any further problems.

**Comment by flyz1** [comment]
> It's my pleasure. I am closing this issue. Please feel free to reach out to me if you have any further problems.

Sorry, I was a little confused after running your dogs and flowers pre-training model. I would like to ask why the results are not as good as the images shown in your results.
![image](https://user-images.githubusercontent.com/43409572/99876625-e6f90b00-2c32-11eb-879c-a7076a17ce83.png)
![image](https://user-images.githubusercontent.com/43409572/99876634-fa0bdb00-2c32-11eb-9f36-d4afa0ffea96.png)
![image](https://user-images.githubusercontent.com/43409572/99876637-0132e900-2c33-11eb-8d6e-de65ea044ab3.png)
![image](https://user-images.githubusercontent.com/43409572/99876642-0c861480-2c33-11eb-82f7-ba0e4a5fd963.png)
![image](https://user-images.githubusercontent.com/43409572/99876645-10b23200-2c33-11eb-8087-cd74d8da7fed.png)
![image](https://user-images.githubusercontent.com/43409572/99876647-1576e600-2c33-11eb-96b8-060538b19186.png)

**Comment by jiupinjia** [comment]
Hi, can you give me more details on the config parameters of your running? e.g., the command line you were using.

**Comment by flyz1** [comment]
> Hi, can you give me more details on the config parameters of your running? e.g., the command line you were using.

Sorry, I have tested the model after adjusting the parameters and found the result is ok. I'm sorry to bother you.

**Comment by jiupinjia** [comment]
Never mind. Glad to see you solved this problem. Please feel free to reach out to me if you have any further problem.
